Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@kunalranglani 
0
04kunalranglani/SampleCoreWebApp
 Code Issues 0 Pull requests 0 Actions Projects 0 Wiki Security Insights Settings
SampleCoreWebApp/azure-pipelines.yml
@kunalranglani kunalranglani Inject AppInsights (#16)
3d9c867 on Jul 26
46 lines (40 sloc)  1.39 KB
  
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'SampleCoreWebApp'
  webAppName: 'sampleappcore'
  solution: '**/*.sln'

steps:
- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Building ASP.Net Core App'

- task: DotNetCoreCLI@2
  displayName: 'Preparing Package to be Deployed'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureCLI@1
  displayName: 'Provisioning Azure Resources'
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptLocation: inlineScript
    inlineScript: |
     az group create --location westus --name $rgName
     az appservice plan create --name $appServiceName --resource-group $rgName --sku FREE
     az webapp create --name $webAppName --resource-group $rgName --plan $appServiceName
  env:
    rgName: appResourceGroup
    appServiceName: newAppService
    webAppName: $(webAppName)

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploying $(webAppName) to Azure App Service'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(azureSubscription)
    appType: 'webAppLinux'
    WebAppName: $(webAppName)
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
© 2019 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
